# -*- coding: utf-8 -*-
"""Online Payments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ylQBLrzc59RXD96mRKPyFxXnN3Su982H
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/PS_20174392719_1491204439457_log.csv")
df.head()

df.isnull().sum()

df.type.value_counts()

type = df["type"].value_counts()
transcations = type.index
quantity = type.values

import plotly.express as px
figure = px.pie(df,
                values = quantity,
                names = transcations, hole = 0.5,
                title = "Distribution of Transcations Type" )
figure.show()

"""### Now let’s have a look at the correlation between the features of the data with the isFraud column"""

# Checking correlation
numeric_df = df.select_dtypes(include=np.number)
correlation = numeric_df.corr()
print(correlation["isFraud"].sort_values(ascending=False))

"""### Now let’s transform the categorical features into numerical. Here I will also transform the values of the isFraud column into No Fraud and Fraud labels to have a better understanding of the output:"""

df["type"] = df["type"].map({"CASH_OUT": 1, "PAYMENT": 2,
                                 "CASH_IN": 3, "TRANSFER": 4,
                                 "DEBIT": 5})
df["isFraud"] = df["isFraud"].map({0: "No Fraud", 1: "Fraud"})
print(df.head())

"""### Now let’s train a classification model to classify fraud and non-fraud transactions. Before training the model, I will split the data into training and test sets"""

# splitting the data
from sklearn.model_selection import train_test_split
x = np.array(df[["type", "amount", "oldbalanceOrg", "newbalanceOrig"]])
y = np.array(df[["isFraud"]])

# training a machine learning model
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.10, random_state=42)

# Identify rows with NaN in ytrain and ytest
nan_mask_train = pd.isna(ytrain).flatten()
nan_mask_test = pd.isna(ytest).flatten()

# Filter xtrain, ytrain, xtest, and ytest to remove NaN rows
xtrain_cleaned = xtrain[~nan_mask_train]
ytrain_cleaned = ytrain[~nan_mask_train]

xtest_cleaned = xtest[~nan_mask_test]
ytest_cleaned = ytest[~nan_mask_test]

model = DecisionTreeClassifier()
model.fit(xtrain_cleaned, ytrain_cleaned)
print(model.score(xtest_cleaned, ytest_cleaned))

"""###Now let’s classify whether a transaction is a fraud or not by feeding about a transaction into the model"""

# prediction
#features = [type, amount, oldbalanceOrg, newbalanceOrig]
features = np.array([[4, 9000.60, 9000.60, 0.0]])
print(model.predict(features))